import { Product } from "@/types";

export const products: Product[] = [
  {
    id: "1",
    name: "Wooden Dining Table",
    nameAr: "طاولة طعام خشبية",
    price: 4500,
    description: "Elegant solid wood dining table made from high-quality beech wood. Perfect for family gatherings.",
    descriptionAr: "طاولة طعام أنيقة من خشب الزان الصلب عالي الجودة. مثالية للتجمعات العائلية.",
    image: "https://images.unsplash.com/photo-1615066390971-03e4e1c36ddf?w=800&q=80",
    category: "furniture",
    woodType: "زان",
    dimensions: "160 × 90 × 75 سم",
    customizable: true,
  },
  {
    id: "2",
    name: "Wall Shelf",
    nameAr: "رف حائط خشبي",
    price: 850,
    description: "Minimalist wooden wall shelf, perfect for books and decorative items.",
    descriptionAr: "رف حائط خشبي بتصميم بسيط وأنيق، مثالي للكتب والديكورات.",
    image: "https://images.unsplash.com/photo-1595428774223-ef52624120d2?w=800&q=80",
    category: "decor",
    woodType: "صنوبر",
    dimensions: "80 × 20 × 15 سم",
    customizable: true,
  },
  {
    id: "3",
    name: "Wooden Gift Box",
    nameAr: "صندوق هدايا خشبي",
    price: 350,
    description: "Handcrafted wooden gift box with elegant finish. Can be customized with engraving.",
    descriptionAr: "صندوق هدايا خشبي مصنوع يدوياً بتشطيب أنيق. يمكن تخصيصه بالنقش.",
    image: "https://images.unsplash.com/photo-1606107557195-0e29a4b5b4aa?w=800&q=80",
    category: "gifts",
    woodType: "بلوط",
    dimensions: "25 × 15 × 10 سم",
    customizable: true,
  },
  {
    id: "4",
    name: "Wooden Chair",
    nameAr: "كرسي خشبي",
    price: 1200,
    description: "Comfortable solid wood chair with classic design.",
    descriptionAr: "كرسي خشبي مريح بتصميم كلاسيكي من الخشب الصلب.",
    image: "https://images.unsplash.com/photo-1503602642458-232111445657?w=800&q=80",
    category: "furniture",
    woodType: "زان",
    dimensions: "45 × 50 × 90 سم",
    customizable: false,
  },
  {
    id: "5",
    name: "Decorative Wooden Panel",
    nameAr: "لوحة ديكور خشبية",
    price: 650,
    description: "Beautifully carved wooden decorative panel for wall art.",
    descriptionAr: "لوحة ديكور خشبية محفورة بشكل جميل لتعليقها على الحائط.",
    image: "https://images.unsplash.com/photo-1618220179428-22790b461013?w=800&q=80",
    category: "decor",
    woodType: "ماهوجني",
    dimensions: "60 × 40 سم",
    customizable: true,
  },
  {
    id: "6",
    name: "Wooden Coffee Table",
    nameAr: "طاولة قهوة خشبية",
    price: 2200,
    description: "Modern wooden coffee table with clean lines and durable finish.",
    descriptionAr: "طاولة قهوة خشبية عصرية بخطوط نظيفة وتشطيب متين.",
    image: "https://images.unsplash.com/photo-1533090481720-8568745a2f5c?w=800&q=80",
    category: "furniture",
    woodType: "بلوط",
    dimensions: "100 × 60 × 45 سم",
    customizable: true,
  },
  {
    id: "7",
    name: "Wooden Cutting Board",
    nameAr: "لوح تقطيع خشبي",
    price: 280,
    description: "Premium hardwood cutting board, perfect for the kitchen.",
    descriptionAr: "لوح تقطيع من الخشب الصلب الفاخر، مثالي للمطبخ.",
    image: "https://images.unsplash.com/photo-1594282486552-05b4d80fbb9f?w=800&q=80",
    category: "kitchen",
    woodType: "زان",
    dimensions: "40 × 30 × 3 سم",
    customizable: false,
  },
  {
    id: "8",
    name: "Wooden Mirror Frame",
    nameAr: "إطار مرآة خشبي",
    price: 950,
    description: "Elegant wooden frame for mirrors with rustic charm.",
    descriptionAr: "إطار مرآة خشبي أنيق بطابع ريفي جميل.",
    image: "https://images.unsplash.com/photo-1615529328331-f8917597711f?w=800&q=80",
    category: "decor",
    woodType: "صنوبر",
    dimensions: "70 × 50 سم",
    customizable: true,
  },
];

export const categories = [
  { id: "all", name: "الكل", nameEn: "All" },
  { id: "furniture", name: "أثاث", nameEn: "Furniture" },
  { id: "decor", name: "ديكور", nameEn: "Decor" },
  { id: "gifts", name: "هدايا", nameEn: "Gifts" },
  { id: "kitchen", name: "مطبخ", nameEn: "Kitchen" },
];

export const woodTypes = ["زان", "بلوط", "صنوبر", "ماهوجني", "جوز", "أخرى"];

export const paymentMethods = [
  { id: "vodafone_cash", name: "فودافون كاش", icon: "📱" },
  { id: "instapay", name: "إنستا باي", icon: "💳" },
  { id: "fawry", name: "فوري", icon: "🏪" },
  { id: "visa", name: "فيزا / ماستركارد", icon: "💳" },
  { id: "other", name: "طريقة أخرى", icon: "✏️" },
];

export const WHATSAPP_NUMBER = "201551277017"; // 01551277017 with country code
